test("Our first test", () => {
  // Primeiro argumento -> nome do teste | Segundo argumento -> teste
  // throw new Error("Something failed");
});
